Webpack integration + config
anct-cnum/portail-conseiller pull request #2
Opened 2021-01-26 17:09 UTC by squirrion

Intégration et configuration de Webpack pour utiliser les classes du Design System de l'état à nos composants React
![image](https://user-images.githubusercontent.com/77339872/105877031-d46acb80-5fff-11eb-9479-9d65f3d6af60.png)

2021-01-26 17:17 UTC, loicguillois requested changes

2021-01-26 17:17 UTC, loicguillois commented on webpack.config.js
> +
on ajoute toujours une dernière ligne vide (EOF)

2021-01-26 17:22 UTC, loicguillois approved these changes

2021-01-26 17:25 UTC, merged

2021-02-02 17:09 UTC, jystervinou reviewed
OK