Liste de redirection pour le bouton de Accompagnement redirection
anct-cnum/portail-conseiller pull request #210
Opened 2022-02-02 08:27 UTC by Ornella452

2022-02-02 11:30 UTC, loicguillois requested changes

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [array2, __] = useState(['atelier', 'individuel']);
évites de nommer les variables de cette façon, on ne sait pas de quoi ça parle

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [valeurInput, setValeurInput] = useState('');
nom de variable trop générique

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [openList, setOpenList] = useState(false);
nom de variable trop générique

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
le nom du fichier est trop générique, vu qu'il s'agit d'un composant spécifique il devrait faire mention de la fonctionnalité métier

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [array, _] = useState([
pourquoi tu utilises le state pour ce tableau ? à quoi sert l'underscore ?

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +          { height: '144px', borderRadius: '0 0 20px 20px', position: 'relative', border: 'solid 1px #5398FF', maxHeight: '250px' } : { height: '144px' }}
utilises plutôt des classes CSS

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/BigRadioButton.js
> +            {value === 'redirection' && controlSelected === value && option !== '' ? option : label}
évites de mettre de la logique dans le code HTML, crées plutôt une fonction.

2022-02-02 11:30 UTC, loicguillois commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +  const [array, _] = useState([
pareil, pas compris pourquoi c'est dans le state. le nom de variable est également trop générique

2022-02-02 13:40 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
le nommage du fichier été déjà comme ça , as tu une proposition pour le renommer ?

2022-02-02 13:41 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [array, _] = useState([
effectivement je peux me passer du useState , (l'underscore, je l'ai ajouter pour éviter que j'ai l'erreur comme quoi je l'utilise jamais )

2022-02-02 14:34 UTC, MorganP-projects commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
on va éviter de le faire dans l'immédiat, comme on est deux à retoucher le même formulaire !
Par contre tu n'as pas créé de composant spécifique à ta liste ?

2022-02-02 14:36 UTC, MorganP-projects commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
Ok vu dans un autre commit (SelectAccompagnement)

2022-02-03 21:02 UTC, squirrion commented on assets/css/cra.scss
> +    font-family: 'MarianneMedium', Arial, sans-serif!important;
vraiement besoin du important ici ?

2022-02-03 21:05 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
Il s'agit bien d'un composant générique pour plusieurs questions (canal, activité, accompagnements notamment)

2022-02-03 21:09 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [array, _] = useState([
Pour le coup effectivement, avec ce select, il faudrait le mettre à part dans un autre type de bouton car trop spécifique par rapport aux autres

2022-02-03 21:10 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +  const [array, _] = useState([
(ca fait trop de modif dans le BigRadioButton)

2022-02-03 21:13 UTC, squirrion commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +  const lieuxReorientation = [
La déclaration du contenu est réalisé à 2 endroits. Il faut le faire qu'à un endroit et le passer en props. Mais si tu remet en composant à part l'accompagnement, tu n'auras pas besoin de passer en props ce contenu

2022-02-03 21:13 UTC, squirrion commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +          <li style={{ padding: '1em 2em', textAlign: 'left' }} className="selecteurList" onClick={() => setChampAutre('')} key={key} value={opt}>
classe ?

2022-02-03 21:14 UTC, squirrion commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +      <div style={{ display: 'flex', paddingBottom: '1 rem' }}>
normal l'espace entre 1 et rem ?

2022-02-03 21:15 UTC, squirrion commented on src/components/connected/cra/Components/SmallRadioButton.js
> +  const lieuxReorientation = [
Donc effectivement là on a une 3ème déclaration. A exporter dans un fichier à part et l'importer

2022-02-03 21:16 UTC, squirrion commented on src/components/connected/cra/Components/SmallRadioButton.js
> +import React, { useState } from 'react';
Pareil trop de modifs dans le SmallRadioButton. Ca me parait + spécifique par rapport aux autres. Il faudrait faire un composant à part comme pour le big

2022-02-03 21:36 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +import React, { useState } from 'react';
Mais effectivement là trop de modifs spécifiques , il faut donc sortir la partie qui évolue dans un autre composant

2022-02-07 13:48 UTC, Ornella452 commented on assets/css/cra.scss
> +    font-family: 'MarianneMedium', Arial, sans-serif!important;
non pas obligé

2022-02-07 13:56 UTC, Ornella452 commented on src/components/connected/cra/Components/SmallRadioButton.js
> +import React, { useState } from 'react';
oui du coup là maintenant il y a 3 composants pour le bouton en mode select et je laisse l'autre composant qui est "générique" sans nouvelle modifs

2022-02-08 20:13 UTC, squirrion commented on src/components/connected/cra/Accompagnement.js
> -import SmallRadioButton from './Components/SmallRadioButton';
👍 OK à voir mais il y a surement le case Accompagnement du switch à supprimer dans les BigRadioButton et SmallRadioButton

2022-02-08 20:13 UTC, squirrion commented on assets/css/cra.scss
> +    font-family: 'MarianneMedium', Arial, sans-serif!important;
Oki tu pourras l'enlever alors

2022-02-08 20:14 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +import { lieuxReorientation } from '../utils/ArrayLieuxReorientation.json';
Pour le nom de fichier tu peux juste mettre LieuxReoritentation.json (pas besoin du type dans le nom)

2022-02-09 17:55 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +        const organisme = null;
En fait je ne pense pas que tu aies besoin de modifier ici pour BigRadioButton et le SmallRadioButton plus bas car le case peut etre viré du coup ?

2022-02-10 10:05 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButton.js
> +        const organisme = null;
en faite si je le met pas , le organisme est undefined et ça provoque une erreur dans la console !
sinon au lieux de faire faire ça , je peux faire une condition dans le state pour gérer cela ?!

2022-02-10 19:40 UTC, squirrion commented on src/reducers/craReducer.js
> +  organisme: null
ok tu peux le supprimer normalement

2022-02-10 19:42 UTC, squirrion commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +              </svg>
Mettre en fichier svg ?

2022-02-10 19:43 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +function BigRadioButtonSlectAccompagnement({ type, label, value, image, imageSelected, heightImage, classDiv }) {
BigRadioButtonSelectAccompagnement

2022-02-10 19:43 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +export default BigRadioButtonSlectAccompagnement;
BigRadioButtonSlectAccompagnement

2022-02-10 19:56 UTC, squirrion commented on src/components/connected/cra/utils/ArrayLieuxReorientation.json
> +{
le nom du fichier : enlever array

2022-02-10 19:57 UTC, squirrion commented on src/components/connected/cra/Components/BigRadioButton.js
> +        const organisme = null;
Ok vu ensemble - paramètre optionnel directement dans actions setté à null

2022-02-10 22:52 UTC, Ornella452 commented on src/components/connected/cra/Accompagnement.js
> +          <BigRadioButtonSelectAccompagnement
oui tu as raison !

2022-02-10 22:54 UTC, Ornella452 commented on src/components/connected/cra/Accompagnement.js
> +          <BigRadioButtonSelectAccompagnement
j'opte pour Redirection !

2022-02-11 07:59 UTC, squirrion commented on src/reducers/craReducer.js
> +  organisme: null
je me rappelle plus du coup : si on ne met pas d'accompagnement comme c'est optionnel : c'est null par défaut ? 
Du coup est- ce que ca mettra accompagnement et organisme à null si non choisi ?

2022-02-11 09:56 UTC, squirrion approved these changes

2022-02-11 16:51 UTC, Ornella452 commented on src/components/connected/cra/Components/SelectAccompagnement.js
> +              <svg width="18px" height="16px" viewBox="0 0 18 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink">
fait

2022-02-11 16:57 UTC, Ornella452 commented on src/components/connected/cra/Accompagnement.js
> +import BigRadioButtonSelectAccompagnement from './Components/BigRadioButtonSelectAccompagnement';
alors pour ce cas , je pense qu'il y a besoin car il y a 2 boutons différent selon la taille de l'écran

2022-02-11 17:24 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +  const onClickRadio = e => {
fait

2022-02-11 17:28 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +      if (openSelectRedirection) {
alors j'ai besoin de laisse cette condition car cela me sert de fermer le select quand la personne à cliquer sur l'une des valeurs

2022-02-14 09:36 UTC, Ornella452 commented on src/components/connected/cra/Components/BigRadioButtonSelectAccompagnement.js
> +      if (openSelectRedirection) {
c'est ok avec => setOpenSelectRedirection(!openSelectRedirection);

2022-02-14 09:48 UTC, MorganP-projects approved these changes

2022-02-14 09:50 UTC, squirrion commented on src/components/connected/cra/utils/CraFunctions.js
> +export function valueMinuscule(value) {
```suggestion
export function changeToMinusculeWithTrim(value) {
```

2022-02-14 09:56 UTC, squirrion approved these changes

2022-02-14 09:59 UTC, merged