Ajout profil admin coop
anct-cnum/portail-conseiller pull request #89
Opened 2021-08-05 10:16 UTC by MorganP-projects

- Accès à l'espace coop pour un "admin COOP"
- Page de connexion pour administrateur
- Page d'inscription pour structure (ne sera pas utilisé pour le moment)

2021-08-05 12:24 UTC, squirrion commented on src/components/Header.js
> +                  {role === 'admin COOP' &&
@MorganP-projects Cela veut dire qu'il faut gérer aussi admin COOP pour la déconnexion => diriger vers /login?role=admin 
Ligne 74 :`<Link className="rf-btn rf-btn--sm" to="/login" title="Se déconnecter">`

2021-08-05 12:25 UTC, squirrion commented on src/components/admin/Welcome.js
> +  useEffect(() => {
@MorganP-projects Normal de conserver ce useEffect ? (comme ici on est admin)

2021-08-05 12:26 UTC, squirrion commented on src/components/admin/Welcome.js
> +  //Forcer affichage en haut de la page pour voir le flashbag
@MorganP-projects A supprimer je pense cette partie

2021-08-05 12:27 UTC, squirrion commented on src/components/anonymous/ChoosePassword.js
> +                      Création de votre compte Mattermost <br className="br-titre" />
@MorganP-projects y aura Mattermost ? (pas vu côté API)

2021-08-05 12:33 UTC, squirrion commented on src/services/user.service.js
> -    if (data.user?.roles[0] !== 'conseiller' && data.roles[0] !== 'conseiller') {
@MorganP-projects Je ne sais plus la raison exact mais ici on verifiait à la fois que data.user?.roles et data.roles contenait bien 'conseiller' sinon logout.
Du coup ici, on passerait en mode si l'un ou l'autre contient 'conseiller' ou 'admin Coop' (peut etre un impact)

2021-08-05 12:50 UTC, loicguillois commented on src/actions/user.actions.js
> +  if (user.roles.includes('admin COOP')) {
`admin_coop` du coup

2021-08-05 12:50 UTC, loicguillois commented on src/components/anonymous/ChoosePassword.js
> +                      Création de votre compte Mattermost <br className="br-titre" />
pareil, pas compris ce lien. pour ces utilisateurs là (BDT, ANCT etc.)  on leur a déjà envoyé un lien de création de compte et ils passent par nous. on ne va pas automatiser pour eux.

2021-08-05 12:50 UTC, loicguillois commented on src/components/anonymous/ChoosePassword.js
> +                      Création de votre compte Mattermost <br className="br-titre" />
ça devient compliqué ce fichier, je pense qu'il vaut mieux en faire deux, un pour les admin et un pour les conseillers `ChoosePasswordAdmin.js` et `ChoosePasswordConseiller.js`, ça simplifierait les choses

2021-08-05 12:50 UTC, loicguillois commented on src/components/connected/Home.js
>        { user?.role === 'conseiller' && (!conseiller || conseiller?.sexe !== undefined) &&
pourquoi faire une vérification sur le sexe ? il faudrait mettre tout ce code dans une fonction pour que ce soit plus clair : genre `isConnected()`

2021-08-06 08:05 UTC, MorganP-projects commented on src/components/admin/Welcome.js
> +  //Forcer affichage en haut de la page pour voir le flashbag
Oui j'enlève tout !

2021-08-06 08:13 UTC, MorganP-projects commented on src/services/user.service.js
> -    if (data.user?.roles[0] !== 'conseiller' && data.roles[0] !== 'conseiller') {
Oui du coup je regarde si les rôles contiennent bien conseiller ou admin_coop pour autoriser l'accès.
Après avoir testé les fonctionnalité côté conseiller, il n'y a pas d'impact.

2021-08-06 08:56 UTC, MorganP-projects commented on src/components/anonymous/ChoosePassword.js
> +                      Création de votre compte Mattermost <br className="br-titre" />
Ici c'était pour les structures pas pour la BDT, mais je supprime, on verra quand on invitera les structures.

2021-08-06 09:01 UTC, MorganP-projects commented on src/components/connected/Home.js
>        { user?.role === 'conseiller' && (!conseiller || conseiller?.sexe !== undefined) &&
Pour l'affichage de la popin sexe/age.
Ok je fait la fct :)

2021-08-09 07:55 UTC, loicguillois requested changes

2021-08-09 07:55 UTC, loicguillois commented on src/components/connected/Home.js
> +      { ecran === 'formulaire' &&
il vaut mieux utiliser le router pour ça (src/App.js)

2021-08-09 07:55 UTC, loicguillois commented on src/components/connected/Home.js
> +      { ecran === 'admin' &&
il vaut mieux le faire dans le composant connected (src/componentes/connected/index.js)

2021-08-09 07:55 UTC, loicguillois commented
je t'ai laissé des commentaires qui permettront de faciliter la navigation utilisateur et d'éviter d'avoir du code trop complexe par la suite

2021-08-09 08:03 UTC, squirrion commented on src/actions/user.actions.js
> +function getEcran(user, sexe) {
@MorganP-projects C'est une préférence mais ici je l'aurai plutôt nommé getHomeRoot ou autre mais en anglais comme le reste du fichier

2021-08-10 12:59 UTC, loicguillois approved these changes

2021-08-10 13:36 UTC, squirrion commented on src/components/connected/index.js
> +      dispatch(conseillerActions.isFormulaireChecked(conseiller.sexe));
@MorganP-projects est-ce qu'il vaut mieux pas garder la même condition qu'auparavant : (!conseiller || conseiller?.sexe !== undefined)

2021-08-11 07:56 UTC, MorganP-projects commented on src/components/connected/index.js
> +      dispatch(conseillerActions.isFormulaireChecked(conseiller.sexe));
Ce n'est plus nécessaire, puisqu'on test l'état dans la fonction :)

2021-08-11 08:25 UTC, squirrion commented on src/components/connected/index.js
> +      dispatch(conseillerActions.isFormulaireChecked(conseiller.sexe));
ah oui ok il y a le if conseiller !!

2021-08-11 08:26 UTC, squirrion approved these changes

2021-08-12 08:01 UTC, merged