ForgottenPassword : Correction wording suite au fix de l'api
anct-cnum/portail-conseiller pull request #92
Opened 2021-08-06 14:17 UTC by MorganP-projects

2021-08-06 14:44 UTC, loicguillois approved these changes

2021-08-06 14:56 UTC, Ornella452 approved these changes

2021-08-06 16:56 UTC, squirrion commented on src/services/user.service.js
> +    if (data?.success) {
@MorganP-projects Possible d'affiner cette condition pour pointer qu'on fait un choix de mot de passe (trop risqué je pense)

2021-08-06 16:57 UTC, squirrion requested changes
Affinage de la condition

2021-08-09 07:07 UTC, squirrion commented on src/services/user.service.js
> +    if (data?.success) {
et je crois pas avoir vu cette modif dans les autres espaces,  je ne sais pas si c'est normal du coup

2021-08-09 08:23 UTC, MorganP-projects commented on src/services/user.service.js
> +    if (data?.success) {
C'est pour endigué le contrôle sur le rôle vu qu'on n'est pas connecté.

2021-08-09 09:20 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
@MorganP-projects Normal ce changement success.successResetPassword ? On peut laisser success comme dans le reducer on a success: action.response ou alors il faut renommer success par  successResetPassword  ici et dans le reducer non ?

2021-08-09 09:36 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
je pense oui ... successResetPassword , il y a eut ce changement ci dans cette PR => https://github.com/anct-cnum/api-conseiller-numerique/pull/341 (je suppose que c'est en lien direct non ?! )

2021-08-09 09:37 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
A moins qu'on fasse dans le reducer `success: action.response.successResetPassword`

2021-08-09 09:43 UTC, MorganP-projects commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
C'est vrai que successResetPassword n'est jamais false, mais si on veut atteindre successResetPassword, c'est soit comme la modif soit success: action.response.successResetPassword

2021-08-09 09:46 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
yes pour success: action.response.successResetPassword. Et du coup dans le useSelectoor associé, ce sera toujours useSelector(state => state.motDePasseOublie.success)

2021-08-09 10:04 UTC, squirrion approved these changes

2021-08-09 11:57 UTC, merged